### ISSUE TITLE
Bug comando

### ISSUE THREAD

**Issue by Itacar** [Lost133/A-Journey-Of-Mods-Galaxy-Modpack-#1]
Não pode se utilizar o mesmo comando 2x seguida e ainda para dificultar tem um cooldown de 5s entre os comandos e se vc utilizar um comado durante esses 5s quando puder usar não vai funcionar por n poder usar 2x o comando

**Comment by Lost133** [comment]
Esse plugin será removido ou reconfigurado em próximos updated ! Peço paciência já que o sever ainda está em fases inicias e está se estabilizando com o tempo.
